added stack
karthik2265/Data-structures-and-Algorithms-Python pull request #5
Opened 2022-10-09 12:55 UTC by Gumanpratapsingh

added new Data Structure in python

2022-10-09 13:05 UTC, karthik2265 commented
make it a class and add push and pop methods.

2022-10-09 13:21 UTC, Gumanpratapsingh commented
Please review and add hacktoberfest label also so that it can be tracked

2022-10-09 13:22 UTC, karthik2265 requested changes

2022-10-09 13:22 UTC, karthik2265 commented on Data-Structures/stack/stack.py
> +        return self.items.pop()
check items is not empty before popping

2022-10-09 13:22 UTC, karthik2265 commented on Data-Structures/stack/stack.py
> +while True:
dont need this taking input from user and stuff. remove this while loop

2022-10-09 13:39 UTC, Gumanpratapsingh commented on Data-Structures/stack/stack.py
> +while True:
should i go with the static one ?
like this ->
    stack.push(1)
    stack.push(2)
    stack.push(3) 
and also popping with the static only
means hardcoded ?

2022-10-09 16:18 UTC, Gumanpratapsingh commented
I have added the trees with its traversal 
Can you check Please 
I have remove the stack as I didn't get about that while loop.
Should we hardcoded that push and pop ? without getting the choice from user 
Please check the trees DS

2022-10-10 04:48 UTC, karthik2265 commented on Data-Structures/stack/stack.py
> +while True:
@Gumanpratapsingh  yes, hardcoded and try to explain with comments what's happening, thanks for contributing.

2022-10-10 11:46 UTC, Gumanpratapsingh commented
Hello Sir,
Can you check?
I have added the requested changes .

2022-10-10 12:03 UTC, merged

2022-10-10 12:10 UTC, Gumanpratapsingh commented
Ok Thanks
Please add the Hacktober-accepted label so it can be tracked.